version: '3.9'
services:
  postgres:
      image: postgres:10
      environment:
          - POSTGRES_USER=user
          - POSTGRES_PASSWORD=pass
          - POSTGRES_DB=dwh
      ports:
        - "5432:5432"
      restart: always

  flask:
    build: .
    container_name: flask_app
    restart: on-failure
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    depends_on:
      - postgres

